OLED_ENABLE = no
OLED_DRIVER = SSD1306
OLED_DRIVER_ENABLE = no # Enables the use of OLED displays
ENCODER_ENABLE = yes       # Enables the use of one or more encoders
LINK_TIME_OPTIMIZATION_ENABLE = yes
LTO_ENABLE = yes
RGBLIGHT_ENABLE = yes      # Enable keyboard RGB underglow
SPLIT_KEYBOARD = yes
CONSOLE_ENABLE = no
